accessing
normalBalance
	"Defined as 'Which side makes the balance go up - credit or debit?' Summarized *from Wikipedia>https://en.wikipedia.org/wiki/Normal_balance*.

Normal balance of common account types:
- Asset: Debit
- Liability: Credit
- Owner's Equity: Credit
- Revenue: Credit
- Expense: Debit
- Retained Earnings: Credit
- Dividend: Debit"

	"Credit as the 'default' is not a domain concept, but prevents duplication to pick one"
	^ #credit