SystemOrganization addCategory: #VirtualStash!
SystemOrganization addCategory: 'VirtualStash-Persistence'!
SystemOrganization addCategory: 'VirtualStash-QuickBooks'!
SystemOrganization addCategory: 'VirtualStash-Receipts'!
SystemOrganization addCategory: 'VirtualStash-Receipts-UI'!
SystemOrganization addCategory: 'VirtualStash-Tesseract'!
SystemOrganization addCategory: 'VirtualStash-Tests'!
SystemOrganization addCategory: 'VirtualStash-UI'!
