"
Equity is the same as ""net worth."" It represents what is left over after you subtract your liabilities from your assets. It can be thought of as the portion of your assets that you own outright, without any debt. (*per GnuCash><https://www.gnucash.org/docs/v4/C/gnucash-guide/chapter_accts.html>)

"
Class {
	#name : #VsEquityAccount,
	#superclass : #VsAccount,
	#category : 'VirtualStash-Core-Bookkeeping'
}
