Class {
	#name : 'VsQbAccountsReceivableAccountType',
	#superclass : 'VsQbAccountType',
	#category : 'VirtualStash-Core-QuickBooks',
	#package : 'VirtualStash-Core',
	#tag : 'QuickBooks'
}

{ #category : 'accessing' }
VsQbAccountsReceivableAccountType class >> description [
	
	^ 'Accounts Receivable'.
]

{ #category : 'accessing' }
VsQbAccountsReceivableAccountType class >> iifDescription [

	^ 'AR'.
]
