Class {
	#name : 'VsQbOtherCurrentLiabilityAccountType',
	#superclass : 'VsQbAccountType',
	#category : 'VirtualStash-Core-QuickBooks',
	#package : 'VirtualStash-Core',
	#tag : 'QuickBooks'
}

{ #category : 'accessing' }
VsQbOtherCurrentLiabilityAccountType class >> description [
	
	^ 'Other Current Liability'.
]

{ #category : 'accessing' }
VsQbOtherCurrentLiabilityAccountType class >> iifDescription [

	^ 'OCLIAB'.
]
