Class {
	#name : 'VsQbLongTermLiabilityAccountType',
	#superclass : 'VsQbAccountType',
	#category : 'VirtualStash-Core-QuickBooks',
	#package : 'VirtualStash-Core',
	#tag : 'QuickBooks'
}

{ #category : 'accessing' }
VsQbLongTermLiabilityAccountType class >> description [
	
	^ 'Long Term Liability'.
]

{ #category : 'accessing' }
VsQbLongTermLiabilityAccountType class >> iifDescription [

	^ 'LTLIAB'.
]
