Class {
	#name : 'VsQbOtherCurrentAssetAccountType',
	#superclass : 'VsQbAccountType',
	#category : 'VirtualStash-Core-QuickBooks',
	#package : 'VirtualStash-Core',
	#tag : 'QuickBooks'
}

{ #category : 'accessing' }
VsQbOtherCurrentAssetAccountType class >> description [
	
	^ 'Other Current Asset'.
]

{ #category : 'accessing' }
VsQbOtherCurrentAssetAccountType class >> iifDescription [

	^ 'OCASSET'.
]
